# Generated by Django 4.1.1 on 2022-09-30 04:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import services._helpers.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Email', 'Email'), ('Message', 'Message')], default=services._helpers.constants.ServiceType['EMAIL'], enum_class=services._helpers.constants.ServiceType, max_length=7)),
                ('service_modal_id', models.IntegerField()),
                ('cadence_time', models.DateTimeField()),
                ('frequency', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Once', 'Once'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default=services._helpers.constants.ScheduleFrequency['ONCE'], enum_class=services._helpers.constants.ScheduleFrequency, max_length=7)),
                ('limit', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('next_exec_date', models.DateTimeField(auto_now_add=True)),
                ('last_exec_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254, unique=True), size=None)),
                ('cc', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None)),
                ('bcc', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
